### ISSUE TITLE
bug(state/txindexer): Pruning `txindex` causes panic

### ISSUE THREAD

**Issue by alesforz** [cometbft/cometbft#4921]
This is a bug affecting the transaction indexer at `cometbft/state/txindex/`.
We encountered it when running e2e test and nightlies on CometBFT `v1.0`, but the same code exists in `main`.

### What Happens
CometBFT panics with the following error:
```bash
2025-02-04 14:49:38 panic: runtime error: invalid memory address or nil pointer dereference
2025-02-04 14:49:38 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185925c]
2025-02-04 14:49:38 
2025-02-04 14:49:38 goroutine 173 [running]:
2025-02-04 14:49:38 github.com/cometbft/cometbft/state/txindex/kv.TxResultByHeight.Less(...)
2025-02-04 14:49:38     github.com/cometbft/cometbft/state/txindex/kv/utils.go:143
2025-02-04 14:49:38 sort.insertionSort({0x1fe3f20, 0xc002dff050}, 0x0, 0x5)
2025-02-04 14:49:38     sort/zsortinterface.go:12 +0xdc
2025-02-04 14:49:38 sort.pdqsort({0x1fe3f20, 0xc002dff050}, 0x0, 0x5, 0x3)
2025-02-04 14:49:38     sort/zsortinterface.go:73 +0x2cc
2025-02-04 14:49:38 sort.Sort({0x1fe3f20, 0xc002dff050})
2025-02-04 14:49:38     sort/sort.go:51 +0x70
2025-02-04 14:49:38 github.com/cometbft/cometbft/state/txindex/kv.(*TxIndex).Prune(0xc00052a340, 0x45d)
2025-02-04 14:49:38     github.com/cometbft/cometbft/state/txindex/kv/kv.go:109 +0x308
2025-02-04 14:49:38 github.com/cometbft/cometbft/state.(*Pruner).pruneTxIndexerToRetainHeight(0xc000022f70, 0x43f)
2025-02-04 14:49:38     github.com/cometbft/cometbft/state/pruner.go:385 +0x8c
2025-02-04 14:49:38 github.com/cometbft/cometbft/state.(*Pruner).pruneIndexesRoutine(0xc000022f70)
2025-02-04 14:49:38     github.com/cometbft/cometbft/state/pruner.go:361 +0x17c
2025-02-04 14:49:38 created by github.com/cometbft/cometbft/state.(*Pruner).OnStart in goroutine 1
2025-02-04 14:49:38     github.com/cometbft/cometbft/state/pruner.go:132 +0x16c
```
### Explanation
The panic can only appear if:
	- the data companion is enabled.
	- a client calls the gRPC API `SetIndexerRetainHeight` to set the retain height to something greater than 0.
	- the pruner tries to prune the transaction indexer.
In practice, before pruning, the pruner sorts the indexed data by height. The panic occurs during this sorting process at [this line](https://github.com/cometbft/cometbft/blob/0991f5945381998c23f02fe831376aa6e356ffbf/state/txindex/kv/kv.go#L118) because the `result` slice contains a `nil` element. The auxiliary [`Less` function](https://github.com/cometbft/cometbft/blob/0991f5945381998c23f02fe831376aa6e356ffbf/state/txindex/kv/utils.go#L139) called during sorting tries to access the `Height` field of a `nil` element, causing the `panic`.

#### Failing `.toml` for e2e tests
You can see the error if you run e2e tests using this `.toml`:
```toml
ipv6 = false
initial_height = 1000
disable_pex = false
key_type = ""
evidence = 200
abci_protocol = "builtin_connsync"
prepare_proposal_delay = "200ms"
process_proposal_delay = "200ms"
check_tx_delay = "20ms"
vote_extension_delay = "100ms"
finalize_block_delay = "500ms"
upgrade_version = ""
load_tx_size_bytes = 0
load_tx_batch_size = 0
load_tx_connections = 0
load_max_txs = 0
log_level = ""
log_format = ""
prometheus = true
block_max_bytes = 0
vote_extension_size = 512
vote_extensions_enable_height = 0
vote_extensions_update_height = -1
peer_gossip_intraloop_sleep_duration = "0s"
experimental_max_gossip_connections_to_persistent_peers = 0
experimental_max_gossip_connections_to_non_persistent_peers = 0
abci_tests_enabled = false
default_zone = ""
pbts_enable_height = 1000
pbts_update_height = -1

[initial_state]

[validators]
  validator01 = 99
  validator02 = 57
  validator03 = 72
  validator04 = 92
  validator05 = 77

[validator_update]
  [validator_update.1010]
    validator06 = 57

[node]
  [node.full01]
    mode = "full"
    version = ""
    seeds = ["seed01"]
    database = "pebbledb"
    privval_protocol = "unix"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 28
    enable_companion_pruning = true
    perturb = []
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.full02]
    mode = "full"
    version = ""
    persistent_peers = ["full01"]
    database = "rocksdb"
    privval_protocol = "file"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 0
    snapshot_interval = 3
    retain_blocks = 0
    enable_companion_pruning = true
    perturb = []
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.full03]
    mode = "full"
    version = ""
    persistent_peers = ["full01", "validator05", "validator04"]
    database = "goleveldb"
    privval_protocol = "unix"
    start_at = 1010
    block_sync_version = "v0"
    state_sync = true
    persist_interval = 5
    snapshot_interval = 0
    retain_blocks = 56
    enable_companion_pruning = true
    perturb = ["disconnect", "restart"]
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.light01]
    mode = "light"
    version = ""
    persistent_peers = ["validator03", "validator04", "validator05", "full02", "validator01", "validator02"]
    database = "rocksdb"
    privval_protocol = ""
    start_at = 1010
    block_sync_version = ""
    state_sync = false
    persist_interval = 0
    snapshot_interval = 0
    retain_blocks = 0
    enable_companion_pruning = false
    perturb = ["upgrade"]
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.light02]
    mode = "light"
    version = ""
    persistent_peers = ["validator03", "validator04", "validator05", "full02", "validator01", "validator02"]
    database = "badgerdb"
    privval_protocol = ""
    start_at = 1015
    block_sync_version = ""
    state_sync = false
    persist_interval = 0
    snapshot_interval = 0
    retain_blocks = 0
    enable_companion_pruning = false
    perturb = []
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.seed01]
    mode = "seed"
    version = ""
    database = "rocksdb"
    privval_protocol = "tcp"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 0
    enable_companion_pruning = false
    perturb = ["kill", "upgrade"]
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.validator01]
    mode = "validator"
    version = ""
    seeds = ["seed01"]
    database = "goleveldb"
    privval_protocol = "tcp"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 0
    enable_companion_pruning = false
    perturb = ["upgrade"]
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.validator02]
    mode = "validator"
    version = ""
    persistent_peers = ["validator01"]
    database = "goleveldb"
    privval_protocol = "tcp"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 1
    snapshot_interval = 3
    retain_blocks = 0
    enable_companion_pruning = true
    perturb = []
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.validator03]
    mode = "validator"
    version = ""
    seeds = ["seed01"]
    database = "pebbledb"
    privval_protocol = "file"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 1
    snapshot_interval = 0
    retain_blocks = 0
    enable_companion_pruning = true
    perturb = ["upgrade", "disconnect", "restart"]
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.validator04]
    mode = "validator"
    version = ""
    persistent_peers = ["validator02", "validator01", "validator03", "full01"]
    database = "rocksdb"
    privval_protocol = "tcp"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 1
    snapshot_interval = 3
    retain_blocks = 0
    enable_companion_pruning = true
    perturb = ["kill"]
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "0s"
  [node.validator05]
    mode = "validator"
    version = ""
    seeds = ["seed01"]
    database = "goleveldb"
    privval_protocol = "unix"
    start_at = 0
    block_sync_version = "v0"
    state_sync = false
    persist_interval = 0
    snapshot_interval = 0
    retain_blocks = 0
    enable_companion_pruning = true
    perturb = []
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "21.516861086s"
  [node.validator06]
    mode = "validator"
    version = ""
    persistent_peers = ["validator01", "full01"]
    database = "goleveldb"
    privval_protocol = "unix"
    start_at = 1005
    block_sync_version = "v0"
    state_sync = true
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 56
    enable_companion_pruning = false
    perturb = []
    send_no_load = false
    zone = ""
    experimental_db_key_layout = ""
    compact = false
    compaction_interval = 0
    discard_abci_responses = false
    indexer = ""
    clock_skew = "2.115850309s"

```

#### Run it
Save the `.toml` above in `test/e2e/networks/failing.toml`.
Then, from `test/e2e` run:
```
make docker runner
./build/runner -f networks/failing.toml
```

**NOTE:** The error is somewhat flaky. You might need to run the e2e test multiple times before it appears.

The `panic` stack trace shown earlier comes from the Docker logs of the validator that panicked. You might see the CLI report a failure in `TestGRPC_BlockIndexerRetainHeight`, but that's not the actual root issue. This go test fails because the validator hosting the pruning service crashes after panicking.
