### ISSUE TITLE
Continue debugging the problem of node falling out of sync

### ISSUE THREAD

**Issue by adizere** [cometbft/cometbft#815]
## Bug Report

This is a continuation of the investigation in issue #521. That issue reported the error:

> ERR Won’t start a peer – switch is not running module=p2p peer={“Data”:{}, “Logger”:{}}

Unlike that issue, we discovered this error does not appear consistently in the logs.
Instead, the node simply falls out of sync with the network, and it is likely caused by the node losing its peers without apparent reason.

### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): v0.34.24 

**Have you tried the latest version**: no

**ABCI app** (name for built-in, URL for self-written if it's publicly available): (osmosis v15.1.0)

**Environment**:
- **OS** (e.g. from /etc/os-release): [15.1.0-alpine](https://hub.docker.com/layers/osmolabs/osmosis/15.1.0-alpine/images/sha256-2432b62ed43f4e1f7a65def31e78f86fc925f5a8248bd34f8044e5e6234f1051?context=explore)

### Config

<details>

<summary>config.toml</summary>

```toml
proxy_app = "tcp://127.0.0.1:26658"
moniker = "osmosis"
fast_sync = true
db_backend = "goleveldb"
db_dir = "data"
log_level = "info"
log_format = "plain"


genesis_file = "config/genesis.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_state_file = "data/priv_validator_state.json"
priv_validator_laddr = ""
node_key_file = "config/node_key.json"
abci = "socket"
filter_peers = false


[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = ["*"]
cors_allowed_methods = ['HEAD', 'GET', 'POST', 'DELETE', 'OPTIONS', 'PATCH', 'PUT',]
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", "Accept-Encoding"]
grpc_laddr = ""
grpc_max_open_connections = 900
unsafe = false
max_open_connections = 900
max_subscription_clients = 100
max_subscriptions_per_client = 5

experimental_subscription_buffer_size = 200
experimental_websocket_write_buffer_size = 200
experimental_close_on_slow_client = false

timeout_broadcast_tx_commit = "10s"
max_body_bytes = 1000000
max_header_bytes = 1048576
tls_cert_file = ""
tls_key_file = ""
pprof_laddr = "localhost:6060"

[p2p]
laddr = "tcp://0.0.0.0:26656"
external_address = ""
seeds = "[edited]"
persistent_peers = ""
upnp = false
addr_book_file = "config/addrbook.json"
addr_book_strict = true
max_num_inbound_peers = 320
max_num_outbound_peers = 160
unconditional_peer_ids = ""
persistent_peers_max_dial_period = "0s"
flush_throttle_timeout = "100ms"
max_packet_msg_payload_size = 1024
send_rate = 5120000
recv_rate = 5120000
pex = true
#
seed_mode = false
private_peer_ids = ""
allow_duplicate_ip = false
handshake_timeout = "20s"
dial_timeout = "3s"

[mempool]
recheck = true
broadcast = true
wal_dir = ""
size = 10000
max_txs_bytes = 1073741824
cache_size = 10000
keep-invalid-txs-in-cache = false
max_tx_bytes = 1048576
max_batch_bytes = 0

[statesync]
enable = false

rpc_servers = ""
trust_height = 0
trust_hash = ""
trust_period = "112h0m0s"
discovery_time = "15s"
temp_dir = ""
chunk_request_timeout = "10s"
chunk_fetchers = "4"

[fastsync]
version = "v0"

[consensus]

wal_file = "data/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

double_sign_check_height = 0

skip_timeout_commit = false

create_empty_blocks = true
create_empty_blocks_interval = "0s"

peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

[tx_index]
indexer = "kv"

[instrumentation]
prometheus = true
prometheus_listen_addr = ":26660"
max_open_connections = 3
namespace = "tendermint"
```

</details>

### What happened?

Node stops processing blocks and falls out of sync with the network. Likely caused by lost peers, but unclear.

### What did you expect to happen?

The node continues processing blocks, remains in sync with the networks.

### How to reproduce it

Unclear.

### Logs

Logs *with some editing* here: https://gist.github.com/adizere/b60b4483328f70a9ded7a02eca414fd2

### Some interesting parts of the logs

Successful block processing:

<details>

<summary>Process block: 9527565</summary>

```log
5:04AM INF Timed out dur=4805.514376 height=9527565 module=consensus round=0 step=1
5:04AM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"8217A2B0C27E06BCD12608D320EBCF319D365706518A5BB2B5DEB62DF5C2EC7A","parts":{"hash":"D1162FA845D6B218A3EBBE9192184997B7CC879A6C3176EF31D9FD85205F2639","total":1}},"height":9527565,"pol_round":-1,"round":0,"signature":"/GB+VdFC4t5MJrMfJ2ZXcRA9Kyjy8iJe9dt8w3b9Ys7sp+RW6+3nC7O49VUYVfI3z0bFXnmu9GXXG06xzv4lBQ==","timestamp":"2023-05-08T05:04:21.243840496Z"}
5:04AM INF received complete proposal block hash=8217A2B0C27E06BCD12608D320EBCF319D365706518A5BB2B5DEB62DF5C2EC7A height=9527565 module=consensus
5:04AM INF finalizing commit of block hash={} height=9527565 module=consensus num_txs=6 root=EDDBF0AB651E79247D405C92E94AC644784AF22D5E609007209C77A7D793ED93
5:04AM INF executed block height=9527565 module=state num_invalid_txs=0 num_valid_txs=6
5:04AM INF committed ABCI commit_hash=C322D21F224E192DBA0E6BEA0B119FF118F731AB7450DB7F50F0D9CDC46A2558 height=9527565 retain_height=0
5:04AM INF committed state app_hash=C322D21F224E192DBA0E6BEA0B119FF118F731AB7450DB7F50F0D9CDC46A2558 height=9527565 module=state num_txs=6
5:04AM INF indexed block exents height=9527565 module=txindex
```

</details>

The block after, at height `9527566` never finishes processing:

<details>

<summary>Process block: 9527566</summary>

```log
5:04AM INF Timed out dur=4790.012085 height=9527566 module=consensus round=0 step=1
5:04AM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"327EF3DC5C1A687CF1DFE3F83212D78AEFF541B868AF1ACFA1FAAC601E5CE4EB","parts":{"hash":"7CDA70D452416E471DD3A092A79150EA3EC3B2AA9E3BA2F9CA7860E9EAC582AA","total":1}},"height":9527566,"pol_round":-1,"round":0,"signature":"U/dJgXx0tWCilcvTRmoL8hWf3Px6TrTppN/70g3AawK+ejLyqadrdJ3lOv2Xa35JHo5eE7JS8lbU9PwveY3PDg==","timestamp":"2023-05-08T05:04:27.10577461Z"}
5:04AM INF received complete proposal block hash=327EF3DC5C1A687CF1DFE3F83212D78AEFF541B868AF1ACFA1FAAC601E5CE4EB height=9527566 module=consensus
5:04AM INF finalizing commit of block hash={} height=9527566 module=consensus num_txs=10 root=C322D21F224E192DBA0E6BEA0B119FF118F731AB7450DB7F50F0D9CDC46A2558
5:04AM INF Timed out dur=1000 height=9527566 module=consensus round=0 step=5

```

</details>

<details>

<summary>grep by 'Ensure peers' overview</summary>

```log
5:00AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=26 numToDial=134
5:00AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=28 numToDial=132
5:01AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=28 numToDial=132
5:01AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=29 numToDial=131
5:02AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=31 numToDial=129
5:02AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=31 numToDial=129
5:03AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=31 numToDial=129
5:03AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=32 numToDial=128
5:04AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=32 numToDial=128
    // Adi: This is where block height 9527566 fails to complete
5:04AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=34 numToDial=126
5:05AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=34 numToDial=126
5:05AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=22 numToDial=138
5:06AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=159
5:06AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=12 numToDial=148
5:07AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=12 numToDial=148
5:07AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=11 numToDial=149
    // Adi: 0 connected peers
5:08AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=160
5:08AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=18 numToDial=142
5:09AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=18 numToDial=142
5:09AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=20 numToDial=140
```

</details>

---

### Acceptance criteria

- [ ] Confirm the root cause: the CacheKV store or IAVL deadlock in the SDK/app
    - See context in the discussion of this issue
- [ ] Open follow-up issue to capture problem & requirements on (p2p + consensus + ABCI queries) sharing a single mutex
    - other teams (including dYdX and Vocdoni) have signalled this problem to us separately
