### ISSUE TITLE
e2e: Generate prometheus.yaml when Prometheus is enabled

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#899]
### Summary

When Promethus is enabled in the manifest, create automatically a configuration file for Prometheus that includes essential settings and the IP addresses of the nodes in the manifest.

For example, for `test/e2e/networks/simple.toml`, which has 4 nodes, the content of the yaml file could be:
```
global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'validator01'
    static_configs:
      - targets: ['localhost:6701']

  - job_name: 'validator02'
    static_configs:
      - targets: ['localhost:6702']

  - job_name: 'validator03'
    static_configs:
      - targets: ['localhost:6703']

  - job_name: 'validator04'
    static_configs:
      - targets: ['localhost:6704']
```
